"""
Event Logs page - View all OneSignal events in real-time.
"""

import flet as ft
from context import AppCtx

LOG_COLORS = {
    "info": ft.Colors.GREY_800,
    "success": ft.Colors.GREEN_700,
    "warning": ft.Colors.ORANGE_700,
    "error": ft.Colors.RED_700,
    "debug": ft.Colors.BLUE_700,
}


@ft.component
def EventLogsPage():
    """
    Page for viewing all OneSignal events in real-time.
    """
    ctx = ft.use_context(AppCtx)
    state = ctx.state

    def clear_logs(e):
        state.clear_logs()

    def copy_logs(e):
        logs_text = "\n".join(
            f"[{log['time']}] [{log['level'].upper()}] {log['message']}" for log in state.logs
        )
        if logs_text:
            e.page.set_clipboard(logs_text)
            state.add_log("Logs copied to clipboard", "success")

    # Build log entries
    log_entries = []
    for log in state.logs:
        color = LOG_COLORS.get(log["level"], ft.Colors.GREY_800)
        level_icon = {
            "info": ft.Icons.INFO_OUTLINE,
            "success": ft.Icons.CHECK_CIRCLE_OUTLINE,
            "warning": ft.Icons.WARNING_AMBER,
            "error": ft.Icons.ERROR_OUTLINE,
            "debug": ft.Icons.BUG_REPORT,
        }.get(log["level"], ft.Icons.CIRCLE)

        log_entries.append(
            ft.Container(
                content=ft.Row(
                    [
                        ft.Icon(level_icon, size=16, color=color),
                        ft.Text(
                            f"[{log['time']}]",
                            size=11,
                            color=ft.Colors.GREY_600,
                            font_family="monospace",
                        ),
                        ft.Text(
                            log["message"],
                            size=12,
                            color=color,
                            selectable=True,
                            expand=True,
                        ),
                    ],
                    spacing=8,
                ),
                padding=ft.padding.symmetric(vertical=4),
            )
        )

    return ft.Container(
        content=ft.Column(
            [
                # Header
                ft.Row(
                    [
                        ft.Row(
                            [
                                ft.Icon(ft.Icons.LIST_ALT, size=28),
                                ft.Text(
                                    "Event Logs",
                                    size=24,
                                    weight=ft.FontWeight.BOLD,
                                ),
                            ],
                            spacing=10,
                        ),
                        ft.Row(
                            [
                                ft.IconButton(
                                    icon=ft.Icons.COPY,
                                    tooltip="Copy all logs",
                                    on_click=copy_logs,
                                ),
                                ft.IconButton(
                                    icon=ft.Icons.DELETE_OUTLINE,
                                    tooltip="Clear logs",
                                    on_click=clear_logs,
                                ),
                            ],
                            spacing=0,
                        ),
                    ],
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                ),
                # Description
                ft.Text(
                    "View all OneSignal events in real-time. "
                    "Events are generated by actions executed on other pages "
                    "and by configured event handlers (notifications, IAM, etc).",
                    size=14,
                    color=ft.Colors.GREY_700,
                ),
                ft.Divider(height=20),
                # Event types legend
                ft.Text("Event Types", weight=ft.FontWeight.W_600),
                ft.Wrap(
                    [
                        ft.Container(
                            content=ft.Row(
                                [
                                    ft.Icon(
                                        ft.Icons.NOTIFICATIONS, size=14, color=ft.Colors.BLUE_700
                                    ),
                                    ft.Text("Notification Click", size=11),
                                ],
                                spacing=4,
                            ),
                            padding=ft.padding.all(4),
                        ),
                        ft.Container(
                            content=ft.Row(
                                [
                                    ft.Icon(
                                        ft.Icons.NOTIFICATIONS_ACTIVE,
                                        size=14,
                                        color=ft.Colors.PURPLE_700,
                                    ),
                                    ft.Text("Notification Foreground", size=11),
                                ],
                                spacing=4,
                            ),
                            padding=ft.padding.all(4),
                        ),
                        ft.Container(
                            content=ft.Row(
                                [
                                    ft.Icon(ft.Icons.SECURITY, size=14, color=ft.Colors.GREEN_700),
                                    ft.Text("Permission Change", size=11),
                                ],
                                spacing=4,
                            ),
                            padding=ft.padding.all(4),
                        ),
                        ft.Container(
                            content=ft.Row(
                                [
                                    ft.Icon(ft.Icons.PERSON, size=14, color=ft.Colors.ORANGE_700),
                                    ft.Text("User Change", size=11),
                                ],
                                spacing=4,
                            ),
                            padding=ft.padding.all(4),
                        ),
                        ft.Container(
                            content=ft.Row(
                                [
                                    ft.Icon(ft.Icons.MESSAGE, size=14, color=ft.Colors.TEAL_700),
                                    ft.Text("IAM Events", size=11),
                                ],
                                spacing=4,
                            ),
                            padding=ft.padding.all(4),
                        ),
                    ],
                    spacing=8,
                    run_spacing=4,
                ),
                ft.Divider(height=20),
                # Logs container
                ft.Container(
                    content=ft.Column(
                        controls=log_entries
                        if log_entries
                        else [
                            ft.Container(
                                content=ft.Column(
                                    [
                                        ft.Icon(
                                            ft.Icons.INBOX,
                                            size=48,
                                            color=ft.Colors.GREY_400,
                                        ),
                                        ft.Text(
                                            "No events recorded yet.",
                                            color=ft.Colors.GREY_500,
                                        ),
                                        ft.Text(
                                            "Execute actions on other pages to see logs here.",
                                            size=12,
                                            color=ft.Colors.GREY_400,
                                        ),
                                    ],
                                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                                    spacing=8,
                                ),
                                alignment=ft.alignment.center,
                                padding=40,
                            )
                        ],
                        scroll=ft.ScrollMode.AUTO,
                        auto_scroll=True,
                        spacing=0,
                    ),
                    border=ft.border.all(1, ft.Colors.GREY_300),
                    border_radius=8,
                    bgcolor=ft.Colors.GREY_50,
                    expand=True,
                    padding=12,
                ),
                # Stats
                ft.Container(
                    content=ft.Text(
                        f"Total events: {len(state.logs)}",
                        size=12,
                        color=ft.Colors.GREY_600,
                    ),
                    padding=ft.padding.only(top=8),
                ),
            ],
            spacing=12,
            expand=True,
        ),
        padding=20,
        expand=True,
    )
